In [1]:
import numpy as np

In [4]:
#where() --> returns index numbers in an output
arr = np.array([8,94,8,56,1,3,4,5,7])
print(arr)
res = np.where(arr>10)
print(res)
print(arr[res])

[ 8 94  8 56  1  3  4  5  7]
(array([1, 3]),)
[94 56]


In [5]:
#concatenate()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [9]:
#concatenate for multi-dimensional array
arr1 = np.array([[1,2,7],[3,4,8],[1,5,1]])
arr2 = np.array([[5,6,8],[7,8,3]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[1 2 7]
 [3 4 8]
 [1 5 1]
 [5 6 8]
 [7 8 3]]


In [10]:
#array_split(array_name , split_value)
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
#sorting of array
#sort()

arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(arr)
print(np.sort(arr)) #by default sorts in ascending order\
print(np.sort(arr)[::-1]) #sorts in descending order


[ 1  4  2  7  9  3  5  8  6 10]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [25]:
#zeros()
#its used to create an array filled with zeros
#by default datatype will be float

#for 1-D array
x=np.zeros(4)
print(x)

#for 3-D array
x=np.zeros((3,3),dtype='i')
print(x)

[0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
#ones()
#its used to create an array filled with ones
#by default datatype will be float

#for 1-D array
x=np.ones(4)
print(x)

#for 3-D array
x=np.ones((3,3),dtype='i')
print(x)

[1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
