In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [9]:
#numpy-array()
arr = np.array([1,2,3,4,5,6,7,8,9]) #one-dimensional array
print(arr)

[1 2 3 4 5 6 7 8 9]


In [10]:
# while using methods we use () , while property we only use name of it
# shape property - used to determine dimensions of an array

# for 1D arrray shape returns (n, )
# where n is the numeber of elements

# for 2D array shape returns ( n,m )
# where n is no. of rows and m is no. of columns

print(arr.shape)

(9,)


In [14]:
# Indexing- used to retrieve single information from array3
print(arr)

# 1  2  3 ... the numbers in array are saved as
# 0  1  2 ... these are the index numbers
#-3 -2 -1 ... these can be negative too

print(arr[1])
print(arr[-1])

#slicing- used to retrieve multiple information from array
print(arr[1:4])
print(arr[4:])
print(arr[:4])

#write a program to print array elements in reverse order
print(arr[::-1])

[1 2 3 4 5 6 7 8 9]
2
9
[2 3 4]
[5 6 7 8 9]
[1 2 3 4]
[9 8 7 6 5 4 3 2 1]


In [30]:
#  2-D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

# for creating a array of 2x3 martix
# focus on 2 first, create 2 [] in array
# now in these [], you can enter max 3 elements
np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr[0,1]) #indexing in 2d array

#similarly for 4x3 martix
# then create 4 [] and max 3 elements in it
np.array([[1,2,3],[4,2,5],[7,4,9],[8,7,9]])
print(arr.shape)
print(arr[1,:]) #print second row
print(arr[:,2]) #print third column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(3, 3)
2
(3, 3)
[4 5 6]
[3 6 9]


In [34]:
#dtype proprty - used to determine datatype of array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.dtype)   #output shows int64 that is each element in array can be of max 64 bits

arr = np.array([1,2,3,4,5,6,7,8,9], dtype='i2') #this only uses 16 bits of space
print(arr.dtype)

arr = np.array([1,2,3,4,5,6,7,8,9], dtype='i1') #this only uses 8 bits of space
print(arr.dtype)

int64
int16
int8


In [5]:
# astype() - used to change datatype of array into another data type

arr = np.array([10,20,30])
print(arr.dtype)

arr = arr.astype('float')
print(arr.dtype)
print(arr )

int32
float64
[10. 20. 30.]


In [8]:
arr = np.array([10.2,15.4,19.7,2.4])
print(arr)
arr = arr.astype('int')
print(arr)


[10.2 15.4 19.7  2.4]
[10 15 19  2]


In [ ]:
# copy() and view()
