In [1]:
import numpy as np

In [2]:
# astype() = used to change datatype of array into another datatype

arr = np.array([1,2,3,4])
print(arr.dtype)
print(arr)

arr = arr.astype('float64')
print(arr.dtype)
print(arr)

int64
[1 2 3 4]
float64
[1. 2. 3. 4.]


In [3]:
arr = np.array([1.5,2.5,3.7,4.6], dtype='i')
print(arr.dtype)
print(arr)

int32
[1 2 3 4]


In [4]:
# copy() and view()

# copy() - if you make changes in orignal array , copied array will remain same , and if you make any changes in copied array, it wont affect the orignal array

org_arr = np.array([1,2,3,4,5])
copy_arr = org_arr.copy()

print(org_arr)
print(copy_arr)

copy_arr[1] = 200
print('Orignal array :',org_arr)
print('Copied array :',copy_arr)



[1 2 3 4 5]
[1 2 3 4 5]
Orignal array : [1 2 3 4 5]
Copied array : [  1 200   3   4   5]


In [5]:
# view() - if you make changes in orignal array , copied array will not remain same , and if you make any changes in copied array, it will affect the orignal array

org_arr = np.array([1,2,3,4,5])
view_arr = org_arr.view()

print(org_arr)
print(view_arr)

view_arr[1] = 200
print('Orignal array :',org_arr)
print('Viewed array :',view_arr)

[1 2 3 4 5]
[1 2 3 4 5]
Orignal array : [  1 200   3   4   5]
Viewed array : [  1 200   3   4   5]


In [8]:
# reshape() - used to change the dimensions of an array ( also called as transformation)
# convert 1D into 2D
# convert 2D into 1D ( simplest )

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)

arr = arr.reshape(4,3)
print(arr)
print(arr.shape)

arr = arr.reshape(-1)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [12]:
# convert 2D to 1D

arr = np.array([[1,2,3],[7,8,9]])
print(arr)
print(arr.shape)

arr = arr.reshape(6)
print(arr)
print(arr.shape)

[[1 2 3]
 [7 8 9]]
(2, 3)
[1 2 3 7 8 9]
(6,)


In [13]:
arr = np.array([[1,2,3],[7,8,9]])
arr = arr.reshape(-1)
print(arr)
print(arr.shape)

[1 2 3 7 8 9]
(6,)


In [14]:
arr = np.array([[1,2,3],[7,8,9]])
arr = arr.flatten()
print(arr)
print(arr.shape)

[1 2 3 7 8 9]
(6,)


In [15]:
# how to filter a array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for i in arr:
    if i%2 == 0:
        print(i)

2
4
6
8
10
12


In [19]:
# boolean masking -  returns output in boolean value

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
res = arr > 5
print(res)
print(arr[res])

res1 = arr%2==0
print(res1)
print(arr[res1])

[False False False False False  True  True  True  True  True  True  True]
[ 6  7  8  9 10 11 12]
[False  True False  True False  True False  True False  True False  True]
[ 2  4  6  8 10 12]


In [23]:
# for 2 or more conditions
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
res = (arr > 4) | (arr < 9)
print(arr[res])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
res = (arr > 4) & (arr < 9)
print(arr[res])

[5 6 7 8]


In [25]:
# modifying elements using boolean indexing

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for i in arr:
  print(i+0.25)

1.25
2.25
3.25
4.25
5.25
6.25
7.25
8.25
9.25
10.25
11.25
12.25


In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
copy_arr = arr.copy()
copy_arr[arr%2==0] = 0
print(arr)
print(copy_arr)

for i in copy_arr:
  print(i+0.25)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  0  3  0  5  0  7  0  9  0 11  0]
1.25
0.25
3.25
0.25
5.25
0.25
7.25
0.25
9.25
0.25
11.25
0.25
