In [1]:
import numpy as np

In [4]:
# where() - this returns index numbers as output

arr = np.array([8,94,8,56,1,3,4,5,7])
res = np.where(arr > 5)
print(res)
print(arr[res])

(array([0, 1, 2, 3, 8]),)
[ 8 94  8 56  7]


In [5]:
#concatenate()

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [6]:
# array_split

arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
# sorting of array

arr = np.array([3,2,0,1,8,9,7,5,6])
print(np.sort(arr))  #by default in ascending order
print(np.sort(arr)[::-1])  #by default in descending order

[0 1 2 3 5 6 7 8 9]
[9 8 7 6 5 3 2 1 0]


In [ ]:
#