In [1]:
  # Data Science Libraries

# a.) Numpy
# b.) Pandas
# c.) Matplotlib
# d.) Seaborn

# What Is Data Science ?

'''
Data science is the study of data to extract meaningful insights for business.

Data Science is a combination of multiple disciplines that uses statistics,
data analysis, and machine learning to analyze data and to extract knowledge and
insights from it.

Data science is the domain of study that deals with vast volumes of data using
modern tools and techniques to find unseen patterns, derive meaningful information,
and make business decisions. Data science uses complex machine learning algorithms
to build predictive models.

Data Science is about data gathering, analysis and decision-making.

Data Science is about finding patterns in data, through analysis, and make future predictions.

By using Data Science, companies are able to make:

Better decisions (should we choose A or B)
Predictive analysis (what will happen next?)
Pattern discoveries (find pattern, or maybe hidden information in the data)


Where is Data Science Needed?

Data Science is used in many industries in the world today, e.g. banking,
consultancy, healthcare, and manufacturing.

Examples of where Data Science is needed:

For route planning: To discover the best routes to ship
To foresee delays for flight/ship/train etc. (through predictive analysis)
To create promotional offers
To find the best suited time to deliver goods
To forecast the next years revenue for a company
To analyze health benefit of training
To predict who will win elections

'''

# Numpy

'''

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform,
and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you
can use it freely.

NumPy stands for Numerical Python.

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions
that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

'''

'\n\nNumPy is a Python library used for working with arrays.\n\nIt also has functions for working in domain of linear algebra, fourier transform,\nand matrices.\n\nNumPy was created in 2005 by Travis Oliphant. It is an open source project and you\ncan use it freely.\n\nNumPy stands for Numerical Python.\n\nWhy Use NumPy?\n\nIn Python we have lists that serve the purpose of arrays, but they are slow to process.\n\nNumPy aims to provide an array object that is up to 50x faster than traditional Python lists.\n\nThe array object in NumPy is called ndarray, it provides a lot of supporting functions\nthat make working with ndarray very easy.\n\nArrays are very frequently used in data science, where speed and resources are very important.\n\n'

In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
# array() : used to create 1D or 2D Array
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
# numpy array vs list
list1 = [10,20,30,40,50]
print(list1)

# multiply each element by 2
print(list1*2)

for i in list1:
  print(i*2)

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
20
40
60
80
100


In [5]:
arr = np.array([10,20,30,40,50])
print(arr*2)

[ 20  40  60  80 100]


In [6]:
# array is a collection of similar data type
arr = np.array([10,56.21,'iGurus',True])
print(arr)

['10' '56.21' 'iGurus' 'True']


In [7]:
# numpy array()
arr = np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [8]:
# shape property
# used to determine the dimensions of an array

# for 1D array shape returns (n,)
# where n is the number of elements

# for 2D array shape returns (n,m)
# where n is the number of rows and m is the number of columns

print(arr.shape)

(6,)


In [9]:
# Indexing and Slicing
print(arr)

# 10 20 30 40 50 60
# 0   1  2  3  4  5
# -6  -5 -4 -3 -2 -1

print(arr[2])
print(arr[-1])

print(arr[1:5])

# wap to print array elements in a reverse order
print(arr[::-1])

[10 20 30 40 50 60]
30
60
[20 30 40 50]
[60 50 40 30 20 10]


In [10]:
# 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(4, 2)


In [11]:
# indexing in 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

print(arr[0,2])

# print the second row
print(arr[1,:])

# print the third column
print(arr[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
3
[4 5 6]
[3 6 9]


In [12]:
# dtype property : used to determine the data type of an array
arr = np.array([10,20,30,40,50])
print(arr.dtype)

arr = np.array([10,20,30,40,50],dtype='i2')
print(arr.dtype)

arr = np.array([10,20,30,40,50],dtype='i1')
print(arr.dtype)

int64
int16
int8


In [13]:
# astype() --> used to change the data type of an array into another data type

arr = np.array([10,20,30])
print(arr.dtype)

arr = arr.astype('f')  # float64bits   f32bits
print(arr.dtype)
print(arr)

int64
float32
[10. 20. 30.]


In [14]:
arr = np.array([10.2,20.3,30.4],dtype='i')
print(arr.dtype)
print(arr)

int32
[10 20 30]


In [15]:
# copy()  and  view()
# in copy() if you make any changes in original array , it won't effect copied array
# and if you make any changes in copied array , it won't effect original array

org_arr = np.array([10,20,30,40,50,60])
copied_arr = org_arr.copy()

print(org_arr)
print(copied_arr)

copied_arr[1] = 200
print('Original Array : ',org_arr)
print('Copied Array : ',copied_arr)

[10 20 30 40 50 60]
[10 20 30 40 50 60]
Original Array :  [10 20 30 40 50 60]
Copied Array :  [ 10 200  30  40  50  60]


In [16]:
# in view() if you make any changes in original array , it will effect copied array
# and if you make any changes in copied array , it will effect original array

org_arr = np.array([10,20,30,40,50,60])
copied_arr = org_arr.view()

print(org_arr)
print(copied_arr)

copied_arr[1] = 200
print('Original Array : ',org_arr)
print('Copied Array : ',copied_arr)

[10 20 30 40 50 60]
[10 20 30 40 50 60]
Original Array :  [ 10 200  30  40  50  60]
Copied Array :  [ 10 200  30  40  50  60]


In [17]:
# reshape()
# used to change the dimensions of an array

# convert 1D into 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 12 -->  2X6  6X2  3X4  4X3  12X1  1X12

arr = arr.reshape(2,6)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [18]:
# convert 2D into 1D
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

arr = arr.reshape(6)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


In [19]:
arr = np.array([[1,2,3],[4,5,6]])
arr = arr.reshape(-1)
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [20]:
arr = np.array([[1,2,3],[4,5,6]])
arr = arr.flatten()
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [21]:
# Filter an array
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = arr > 5
print(res)  # BOOLEAN MASKING
print(arr[res])

[False False False  True  True False  True  True False False]
[ 7  8  9 10]


In [22]:
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = arr%2==0
print(res)  # BOOLEAN MASKING
print(arr[res])

[False  True  True False  True False False  True  True  True]
[ 4  2  8 10  2  4]


In [23]:
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = (arr > 4) & (arr < 9)
print(arr[res])

[7 8]


In [24]:
# Modify Elements Using Boolean Indexing
arr = np.array([10,12,15,18,19,21,25,32,35,36])
print(arr)
copied_arr = arr.copy()
copied_arr[arr%2==0] = 0
print(copied_arr)

[10 12 15 18 19 21 25 32 35 36]
[ 0  0 15  0 19 21 25  0 35  0]


In [25]:
# where()  -->  used to return indexNumbers in an output
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = np.where(arr>5)
print(res)

(array([3, 4, 6, 7]),)


In [26]:
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = np.where(arr>5)
print(arr[res])

[ 7  8  9 10]


In [27]:
# concatenate()
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [28]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [29]:
# array_split(arrayName,splitValue)
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
arr = np.array_split(arr1,3)
print(arr)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9]), array([10, 11, 12, 13])]


In [30]:
# sorting of an array
# sort()

arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(np.sort(arr))   # by default it will sort the array in ascending order

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(np.sort(arr)[::-1]) # descending order

[10  9  8  7  6  5  4  3  2  1]


In [32]:
# zeros() it will fill an array with 0's
# default data type is FLOAT

# 1D array
arr = np.zeros(7)
print(arr)

[0. 0. 0. 0. 0. 0. 0.]


In [33]:
# 2D array
arr = np.zeros((3,3),dtype='i')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
# ones() it will fill an array with 1's
# default data type is FLOAT

# 1D array
arr = np.ones(7)
print(arr)

[1. 1. 1. 1. 1. 1. 1.]


In [35]:
# full(size,constantValue)
# used to fill an array with a constant value

x = np.full(9,121)
print(x)

[121 121 121 121 121 121 121 121 121]


In [36]:
x = np.full((3,4),24)
print(x)

[[24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]]


In [37]:
# sum()
print(np.sum(x))

288


In [38]:
# Numpy Random Module
from numpy import random
x = random.randint(100)
print(x)

57


In [39]:
x = random.randint(120,150)
print(x)

129


In [40]:
# rand() method generate a random float value b/w 0 and 1
x = random.rand()
print(x)

0.9219464302346463


In [41]:
arr = random.randint(100,size=(8))
print(arr)

[20 49 81 57 11 69 63 70]


In [42]:
arr = random.randint(20,50,size=(4,5))
print(arr)

[[46 43 33 45 47]
 [33 28 20 31 38]
 [22 34 39 32 36]
 [28 39 48 46 41]]


In [43]:
x = random.rand(5)
print(x)

[0.28651445 0.36178544 0.52133807 0.53170176 0.04946584]


In [44]:
x = random.rand(3,3)
print(x)

[[0.61968972 0.00617838 0.33975722]
 [0.69237231 0.33215066 0.82842771]
 [0.52584758 0.22091764 0.08271965]]


In [45]:
# Numpy Broadcasting
arr1 = np.array([2,3,4])
arr2 = np.array([7,6,8])
print(arr1 + arr2)
print(arr1 * arr2)

[ 9  9 12]
[14 18 32]


In [46]:
# if arrays are of diff dimensions
arr1 = np.array([2,3,4])
arr2 = np.array([7,6])
print(arr1 * arr2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
arr1 = np.array([2,3,4])
arr2 = np.array([7])       # 7 7 7
print(arr1 * arr2)